### ISSUE TITLE
ERROR: test_docs_page (__main__.WebPageBrowsing)

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slateci-unit-tests#6]
Errors during `test_docs_page()`:
```shell
======================================================================
ERROR: test_docs_page (__main__.WebPageBrowsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/slateci.github.io/slateci.github.io/slateci-unit-tests/main.py", line 145, in test_docs_page
    docs_page.iterate_links_doc_content(linkL1, linkL2)
  File "/home/runner/work/slateci.github.io/slateci.github.io/slateci-unit-tests/page.py", line 130, in iterate_links_doc_content
    self.logger.info("Docs Page: {} -> {} -> {}".format(linkL1, linkL2, links[i].text))
IndexError: list index out of range
```

**Comment by adamhgriffith-uofu** [comment]
Promising leads:
* [Disabling PDF Viewer plugin in chromedriver](https://stackoverflow.com/questions/41877155/disabling-pdf-viewer-plugin-in-chromedriver)
* [Override download settings of pdf in web browser with automation](https://itsopensource.com/override-download-settings-of-pdf-in-web-browser-with-automation/)
* [download all pdf file with selenium python](https://www.edureka.co/community/84882/download-all-pdf-file-with-selenium-python)
* [chrome webdriver - PDF documents downloading and not opening in new tab](https://stackoverflow.com/questions/29795160/chrome-webdriver-pdf-documents-downloading-and-not-opening-in-new-tab)

**Comment by adamhgriffith-uofu** [comment]
Weird, tried adding the following without affect:
```python
options.add_experimental_option("prefs",
    {
        "plugins.always_open_pdf_externally": False,
        "plugins.plugins_list": [{
            "enabled": True, "name": "Chrome PDF Viewer"
        }]
    })
```

**Comment by adamhgriffith-uofu** [comment]
Going to have to resort to the super gross hack in `page.py`'s `iterate_links_doc_content()`:
```python
if search('^.*\.pdf$', links[i].get_attribute("href")):
    self.logger.info('PDF download detected: {}'.format(links[i].get_attribute("href")))
else:
    horkle snorkle
```
